### ISSUE TITLE
Updated advertisements

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#101]
We have new ads to replace a lot of the old ones.

Here is the advertisements tracking sheet so you can see what's what:
https://www.dropbox.com/s/4z3ixgwo91dqspd/Advertisement%20Tracking%20Sheet%202016.xlsx?dl=0
The ones that say “new image” means that their new image is saved in the 2016 folder. If there is nothing written in that column, it means they did not send in a revised image and we can print what we already had on file for the 2015 program.
If you need my help deciphering which ad belongs to which organization again, let me know! 

New ads are in this 2016 folder: 
https://www.dropbox.com/sh/wff0bvudw9vpg5t/AADoA-mEjOEEalo02-UsEbDJa?dl=0

**Comment by bjornmeansbear** [comment]
There are two issues. 
1. Concern USA.pdf — This is a different size than the previous add, its supposed to be a 1/2 pager, but the new one looks more like a 2/3 pager? (https://www.dropbox.com/s/494pen3mhuhzg9g/Concern%20USA.pdf?dl=0)
2. ICFP ad 2016 World Vision — This is supposed to be a half-pager as well. Their size is right, but the orientation is vertical, but should be horizontal... it has to be rotated 90degrees to fit in its spot, this probably is not their intention. https://www.dropbox.com/s/i66lq63gte9wrtl/ICFP%20ad%202016%20World%20Vision.pdf?dl=0

**Comment by mkamoss** [comment]
I've asked our RA Christine to look into these issues and will be in touch about resolutions.

**Comment by mkamoss** [comment]
Don't forget you can update what we have so far in the French version too.

**Comment by bjornmeansbear** [comment]
updated and added to both books.
