### ISSUE TITLE
add Chris Elias to Monday opening session

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#102]
You can replace Melinda Gates with Chris Elias, on p. 37 - bio and photo are below

Dr. Chris Elias is the president of the Global Development Program, where he leads the foundation’s efforts in a diverse range of program areas aimed at finding creative new ways to ensure solutions and products get into the hands of people in poor countries who need them most. Focusing on areas with the potential for high-impact, sustainable solutions that can reach hundreds of millions of people, Chris oversees Global Development’s portfolio in Agriculture Development; Emergency Response; Family Planning; Financial Services for the Poor; Maternal, Newborn, & Child Health; Nutrition; Polio Eradication; Vaccine Delivery; and Water, Sanitation & Hygiene. A common theme of these programs is innovative and integrated delivery, including an emphasis on strengthening of primary health care systems.
Chris’s professional background is in public health and medicine. Prior to joining the Gates Foundation in February 2012, he worked in various positions and countries for international nonprofit organizations, most recently serving as the president and CEO of PATH, an international, nonprofit organization dedicated to improving the health of people around the world by advancing technologies, strengthening systems, and encouraging healthy behaviors.
Chris holds an MD from Creighton University, having completed postgraduate training in internal medicine at the University of California San Francisco, and an MPH from the University of Washington, where he was a fellow in the Robert Wood Johnson Clinical Scholars Program. He is a member of the Institute of Medicine.

![chris-elias](https://cloud.githubusercontent.com/assets/16087472/11964509/43697636-a8bc-11e5-871f-14d80f32f3af.jpg)

**Comment by bjornmeansbear** [comment]
This is another image that if possible we should try to get a bigger version of

**Comment by bjornmeansbear** [comment]
Updated. the image is okay if necessary.
