### ISSUE TITLE
create assignments for day at-a-glances

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#104]
Can you create assignments for the day at-a-glances (the long at-a-glances that detail everything that happens on each day)? I'll need to go in there manually to make updates.

**Comment by bjornmeansbear** [comment]
As far as I can tell these are assigned to you? (pages 47-50 for instance all say they are part of the 10November assignment...) Or do you mean in the French docs?

**Comment by mkamoss** [comment]
Yes sorry, in the French docs!

Sent from my iPhone

On Dec 22, 2015, at 11:14 PM, Kristian Bj?rnard <notifications@github.com<mailto:notifications@github.com>> wrote:

As far as I can tell these are assigned to you? (pages 47-50 for instance all say they are part of the 10November assignment...) Or do you mean in the French docs?

##

**Comment by bjornmeansbear** [comment]
okay. These are assigned, the rest of the session days aren't yet though... I need to be able to work at my desk to do those well.
