### ISSUE TITLE
On-site Aux Events edit - add two events to Tuesday, 26 January, 18:00 – 19:30

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#111]
Please add these two on-site aux events at the end of the Tues 18:00 to 19:30 section

![image](https://cloud.githubusercontent.com/assets/16087472/11980632/4e2ddb44-a96a-11e5-9721-4e7c1b11ef7a.png)

**Comment by bjornmeansbear** [comment]
Do you have this as actual text? just as a PNG isn't convenient — I can find on the conference site? The same applies to #112

**Comment by mkamoss** [comment]
Yep, here you go - https://www.dropbox.com/s/cdi5yz8x3mnrtt4/2016OnSiteAuxiliaryEvents_V2.docx?dl=0

I haven't uploaded this to the site yet.

## 

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu

**Comment by bjornmeansbear** [comment]
It looks like you did this in Incopy?
