### ISSUE TITLE
Addition to off-site aux events

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#114]
Please add these 2 events to the end of the off-site aux events section -- I will send you a Word doc.

![image](https://cloud.githubusercontent.com/assets/16087472/12042049/1e9b98dc-ae45-11e5-831f-1dae8fb38209.png)

**Comment by bjornmeansbear** [comment]
These look like you entered them? As far as I can tell they're in the layout.

**Comment by mkamoss** [comment]
OK, cool.
