### ISSUE TITLE
add to Monday opening session, preferably on the page with Robert Blake and Mike Klag

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#115]
Baroness Verma
Parliamentary Under-Secretary of State at the Department for International Development (DFID)

Baroness Verma was appointed Parliamentary Under-Secretary of State at the Department for International Development on 13 May 2015. She is a Conservative member of the House of Lords. In 2006 she was raised to the peerage as Baroness Verma of Leicester in the County of Leicestershire. She was Opposition Whip from 2006 to 2010 and subsequently Government Whip following the 2010 general election. Prior to becoming Parliamentary Under Secretary of State for DFID, Baroness Verma was Parliamentary Under Secretary of State for DECC, Spokesperson for Cabinet Office, International Development, Women and Equalities and Business Innovation and Skills. Baroness Verma attended local schools and university in Leicester.

![baroness verman](https://cloud.githubusercontent.com/assets/16087472/12053826/e823f708-aeea-11e5-8311-6d4383eb28fb.jpg)

**Comment by bjornmeansbear** [comment]
Is there a larger image of her? Again, this is too small.

**Comment by bjornmeansbear** [comment]
this is like 260x174... if it could be at least 500x300 if not larger? 

These all just seem like they've been pulled off FP website? an image like this feels semi-professional and should definitely have a larger version...

**Comment by mkamoss** [comment]
Is this better?

## 

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu

**Comment by bjornmeansbear** [comment]
This fits more or less.... could be better, but its there.
