### ISSUE TITLE
Mktplace of Ideas - FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#116]
Copy is up in the Dropbox. Sorry that it's in a table!

**Comment by bjornmeansbear** [comment]
Should Marketplace of Ideas translate to LE MARCHÉ AUX IDÉES or Foire aux Idées?

There are 2 different documents, and it is LE MARCHÉ AUX IDÉES in the document with the intro paragpraph and Foire aux Idées in the doc with the table of entries.

**Comment by mkamoss** [comment]
## Le Marche, please.

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu

**Comment by bjornmeansbear** [comment]
Okay!
This is all in.
Unfortunately, I had to add 2 pages to this section to fit everything. If that is unacceptable, let me know, I can make the type all smaller and force it to fit in the same # of pages as english...

**Comment by bjornmeansbear** [comment]
Oh, also, its assigned and ready for you.

**Comment by mkamoss** [comment]
Doesn't matter to me, I don't think. They were always going to be different lengths, right? Since French is longer?

**Comment by bjornmeansbear** [comment]
So far most things have been able to be forced to fit cause it was just a couple lines extra. so this is the only section so far where I really needed xtra full pages ... that said, I don't think we've tackled AUX events yet... so that might get much longer
