### ISSUE TITLE
IBP

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#117]
The FR IBP copy looks a little odd -- are you still working on it? Or were you when you made the PDF late last week? See page 28 etc.

**Comment by bjornmeansbear** [comment]
What is IBP?

**Comment by bjornmeansbear** [comment]
Oh, page 28 on. No, I am not working on that, that's in there as left by the Indonesians from before.

**Comment by bjornmeansbear** [comment]
fixed.
