### ISSUE TITLE
Add to youth plenary 

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#119]
Please add to the Youth Plenary bios page -- sorry, I know you'll have to squeeze it in!
(We will also need to add this to the French version. I will get it translated ASAP.)

Benoit Kalasa
Director of the UNFPA Regional Office for West and Central Africa

Benoit Kalasa, a national from the Democratic Republic of Congo, is presently the Director of the Technical Division at UNFPA, where he leads a team of over 60 professionals responsible for providing intellectual guidance to support 6 regional and 129 country UNFPA offices, as well as to global and intergovernmental processes in relation to the ICPD mandate of UNFPA.

Mr. Kalasa has been working with UNFPA since 1999. Most recently he was the Director of the Regional Office for West and Central Africa (WCARO), based in Dakar, Senegal. He also acted as the UNFPA Representative for Madagascar and Country Director for Mauritius, Seychelles and Comoros from 2006 to 2010 followed by being accredited as Representative for Ethiopia from 2010 to December 2012.

Throughout his career he has played a leading role in advocating for the ICPD issues, promoting at the national level the goals of the programme and ensuring the integration of issues of reproductive health, population and development and gender in national plans and policies as well as in the broader development agenda.

Mr. Benoit Kalasa holds a PhD in Economics, with specialization in Economic Demography at the Institute of Political Studies (Sciences Po) in Paris, France.

![benoit1](https://cloud.githubusercontent.com/assets/16087472/12095028/22ecae1e-b2da-11e5-9106-8fc4bfbcc81c.png)

**Comment by mkamoss** [comment]
Here is the FR version -- 
[benoit bio FR.docx](https://github.com/OOKB/icfp/files/77796/benoit.bio.FR.docx)

**Comment by bjornmeansbear** [comment]
Youth plenary is on Wednesday Jan. 27, pg 94-96?

**Comment by bjornmeansbear** [comment]
Added to french and english and assigned. If anyone else needs to be added here, it really isn't possible without adding 2 more pages to the whole book.
