### ISSUE TITLE
delete an aux event

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#121]
on page 221 (ENG booklet), can you please delete the auxiliary event called "Getting the Details Right"? It is on Wednesday morning.
I thought it would be better for you to do this since you will need to adjust the layout accordingly.

I dont' think there is an assignment yet for the French version, so you can either assign it to me, or you can delete it from its respective page there. If you delete it, please remember to delete it from the at-a-glance as well as the full description.
In French, it is: 
Faire attention aux détails : Construire un modèle efficace de planification familiale dans le cadre de la couverture sanitaire universelle  
Marie Stopes International  
Legian 7

**Comment by bjornmeansbear** [comment]
english fixed.
