### ISSUE TITLE
New FR & ENG description for Tuesday lunch plenary

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#123]
[tuesday lunch plenary description_FR.docx](https://github.com/OOKB/icfp/files/77787/tuesday.lunch.plenary.description_FR.docx)
[tuesday lunch plenary description_ENG.docx](https://github.com/OOKB/icfp/files/77788/tuesday.lunch.plenary.description_ENG.docx)

**Comment by bjornmeansbear** [comment]
updated! a much better length based on available space!
