### ISSUE TITLE
FP2020 plenary copy & headshots

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#128]
KB, here is the FP2020 plenary copy. Some of these people are new, some are old and in a different position. And there are now 2 sections rather than the original 3.
If you could put the people in the order they appear in this Word doc, that would be great. 
[fp2020 plenary_final copy.docx](https://github.com/OOKB/icfp/files/79036/fp2020.plenary_final.copy.docx)

I am attaching the new headshots, some of which you may already have, but here they are in the same place.
![ellen-starbird](https://cloud.githubusercontent.com/assets/16087472/12127753/fc19da44-b3c6-11e5-85e4-6c589a84a2ad.png)
![jagdish1](https://cloud.githubusercontent.com/assets/16087472/12127758/fe57cb40-b3c6-11e5-9741-68f8d7f2a3be.jpg)
![baroness_verma_visit_13](https://cloud.githubusercontent.com/assets/16087472/12127771/0b223a04-b3c7-11e5-9e56-eeb1b25dc31b.jpg)
![marie-claude1](https://cloud.githubusercontent.com/assets/16087472/12127774/0f3975da-b3c7-11e5-80f4-539c975e46ca.jpg)

**Comment by mkamoss** [comment]
Also please note - Beth Schlacter is the leader of the discussion for both parts. So she needs to appear first.
If any of my directions are confusing, please review to the FP2020 plenary on this page: http://fpconference.org/2016/program/plenaries/
It is correct.

**Comment by bjornmeansbear** [comment]
french version up to date. doing english version now.
