### ISSUE TITLE
Add to Topical Roundtables - ENG

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#129]
Tuesday
Table 19
Exchanging Ideas on Business Action for Family Planning
Seema Jalan
UN Foundation

Wednesday
Table 18
Decentralization: The Critical Importance of Achieving Subnational Ownership of Family Planning
Duff Gillespie
Advance Family Planning, Bill & Melinda Gates Institute for Population and Reproductive Health, JHSPH

Table 19
Advocating for Family Planning in Francophone Africa (French) [KB: Put "(French)" in itals)
Alison Bodenheimer
Advance Family Planning, Bill & Melinda Gates Institute for Population and Reproductive Health, JHSPH

**Comment by bjornmeansbear** [comment]
english updated.
