### ISSUE TITLE
Add to Topical Roundtables - FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#130]
Tuesday
Table 19
Échange d’idées sur l’action commerciale pour la planification familiale
Seema Jalan
UN Foundation

Wednesday
Table 18
La décentralisation : De l’importance critique de l’appropriation sous-nationale de la planification familiale
Duff Gillespie
Advance Family Planning, Institut Bill & Melinda Gates pour la Santé de la Reproduction, École de Santé Bloomberg, JHSPH

Table 19
Plaidoyer pour la planification familiale en Afrique francophone (française)
Wednesday
Alison Bodenheimer
Advance Family Planning, Institut Bill & Melinda Gates pour la Santé de la Reproduction, École de Santé Bloomberg, JHSPH

**Comment by bjornmeansbear** [comment]
okay! french updated.
