### ISSUE TITLE
mardi 26 janvier - copy change

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#133]
This assignment isn't letting me in -- not sure what's up. Can you assign?

For Jagat Prakash Nadda, delete (invité) and also add Hon. before his name, where it appears under his photo:
Hon. Jagat Prakash Nadda

Then in the first line of his bio, please change to say: Son Honorable Jagat Prakash Nadda

~~Also the FR day assignments all have weird page numbers, FYI.~~

**Comment by bjornmeansbear** [comment]
Strange, it wouldn't let me play with it at first either, but I think I fixed it. I definitely updated his title.
