### ISSUE TITLE
mardi 26 jan FR - plenary description

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#134]
This is the new FR description copy for the Packard plenary.

La Fondation David et Lucile Packard accueillera son deuxième Quality Innovation Challenge, avec pour objectif d’amorcer de nouveaux projets globaux qui amélioreront la qualité des services de planification familiale et de santé de la reproduction. Les participants à cette session pourront écouter les responsables du Programme pour la Population et la Santé de la Reproduction, Tamara Keinin (Directrice) et Lana Dakan (Responsable du programme) qui expliqueront pourquoi la qualité est importante en matière de santé sexuelle et de la reproduction. Numfor Alenwi, un des précédents vainqueurs du Quality Innovation Challenge, qui travaille pour l’Agenda du Cameroun pour le Développement Durable, partagera les connaissances tirées de son approche unique pour dépasser les barrières politiques et sociales et offrir aux filles camerounaises une information et des services SSR de qualité. Il s’agit d’une séance de travail et les participants auront 30 minutes pour développer des propositions, poser des questions, et recevoir un retour des experts dans ce domaine. Les idées soumises en personne au cours de la session du déjeuner, et acceptées jusqu’à 16h le même jour, seront considérées éligibles pour recevoir cinq bourses allant jusqu’à $100,000 chacune. Les finalistes seront annoncés lors de la session plénière de clôture de la CIPF, le jeudi 28 janvier.

Plus de détails concernant le challenge et les précédents vainqueurs sont disponibles en ligne sur www.packard.org/quality.

**Comment by bjornmeansbear** [comment]
updated
