### ISSUE TITLE
additional on-site aux event

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#135]
An on-site aux event was left off the list. Please add to the at-a-glance on p. 206 and create a new section on p. 209 (you may need to adjust the day tabs on the sides of the pages too if things get bumped)

AT A GLANCE - p 206

Monday, 25 January 
(11:00 – 12:30)

Event Title 
Meeting our Commitments: Averting a Family Planning Crisis  

Sponsoring Organization(s)
UNFPA

Room
Singaraja Hall 2

---

DESCRIPTION -  p 209
Monday, 25 January
11:00 – 12:30

First Floor Building 1

LOCATION
Singaraja Hall 2
 TITLE
Meeting our Commitments: Averting a Family Planning Crisis

SPONSORING ORGANIZATION(S)
UNFPA

DESCRIPTION
A changing aid environment and global health architecture are threatening the family planning
space. With traditional donors significantly reducing aid, and the funding available for family
planning reducing even more significantly in proportion to overall funding, there is a tangible risk
that the momentum created by the 2012 London Summit on Family Planning be lost and that the
goals set by the international community at the Summit are not achieved.

UNFPA Supplies (formerly the “Global Programme to Enhance Reproductive Health Commodity
Security”) – the only United Nations programme specifically focused on family planning and
reproductive health commodity security – has a focused mission to ensure a secure, steady and
reliable supply of quality contraceptives and maternal health medicines and to improve access
and use by strengthening national health systems and services. UNFPA Supplies is the largest
procurer of contraceptives globally, and supports national action to reach poor and marginalized
women and girls in countries with high unmet need for family planning and high rates of maternal
death.

A shortage of funding for this Programme through to 2020, could result in 116 million
unintended pregnancies, leading to 55 million live births and 45 million abortions, over 2 million
maternal and child deaths and a loss of $5.5 billion in direct health-care spending.

The international community needs to build on the momentum it has created for family planning,
and come together to ensure the necessary financial in-flow is ensured and the lives and dreams
of millions of women and girls around the world are saved.

Against this backdrop, UNFPA is calling a meeting of family planning and UNFPA Supplies
stakeholders, to discuss how this imminent crisis can be averted.

This session will be in English and French.
Snacks and refreshments will be provided.

**Comment by mkamoss** [comment]
FR version attached.
[aux event - unfpa_FRENCH.docx](https://github.com/OOKB/icfp/files/79299/aux.event.-.unfpa_FRENCH.docx)

**Comment by bjornmeansbear** [comment]
english version, check.
