### ISSUE TITLE
aux events - FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#136]
Did you assign the FR aux events to me?

I need to delete MSI from the list of sponsors for an event on Wednesday evening -- A Celebration of Young People’s Contraceptive Choice
This is more a note for me to remember what I have to delete. But do let me know if I have this assigned. I don't see it in DB.

**Comment by bjornmeansbear** [comment]
almost done...........

**Comment by bjornmeansbear** [comment]
onsites are all in. Offsites coming soon.
