### ISSUE TITLE
MA - add FP2020 to on-site aux event when FR assignment is ready

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#140]
To the on-site aux event - The DRC’s emergence and family planning leadership through 2030 
add FP2020 as a sponsor
when FR assignment is ready

(KB, this is a note for me, not you)

**Comment by bjornmeansbear** [comment]
Is this done? can we close this?

**Comment by mkamoss** [comment]
## Yes, done!

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu
