### ISSUE TITLE
FR day assignments all have weird page numbers, FYI.

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp#143]
@mkamoss weird how? are the page numbers incorrect? or do they look strange in some other way to you?

**Comment by mkamoss** [comment]
I guess they are all individual assignments and not part of a larger InDesign file or something? They all seem to start at page 1.

## 

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu

**Comment by bjornmeansbear** [comment]
So they just don't seem to be numbered correctly for you. Okay. They're showing up for me, so maybe its just some issue related to me getting to see them as a whole and you seeing them individually....... hopefully the PDF will number them correctly.

**Comment by bjornmeansbear** [comment]
Do you still sees these as starting from page number 1?

**Comment by mkamoss** [comment]
PDF seems to have correct numbering, so I think we are OK.
