### ISSUE TITLE
Remove Aux Event in French

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp#144]
In French, it is: 
Faire attention aux détails : Construire un modèle efficace de planification familiale dans le cadre de la couverture sanitaire universelle

Marie Stopes International

Legian 7

**Comment by bjornmeansbear** [comment]
Crap – does this need to be deleted still?
Looks like it is on Tuesday (Mercredi) 27 Janvier

**Comment by mkamoss** [comment]
No, hold on this. I am confused about what we're supposed to do with it. Getting confirmation now.

**Comment by mkamoss** [comment]
Yes, needs to be deleted on both the ENG and FR programs, in the at a glance and in the full list. In ENG, it's 
Leave No One Behind: UHC & Family Planning 
Population Services International & Marie Stopes International
Singaraja Teras

Can you delete?

**Comment by bjornmeansbear** [comment]
removed from English......

**Comment by bjornmeansbear** [comment]
removed from french…………
