### ISSUE TITLE
front matter + demand generation aux events

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#148]
I kind of destroyed the Front Matter ENG -- eek!
and also I need to add some auxiliary sessions under Demand Generation and Social Change, and I don't have enough space to do it.
Here is the Word doc of what needs to be added -- I can add it but I need you to give me enough space, which you can estimate using this Word doc.
[demand generation aux events ENG.docx](https://github.com/OOKB/icfp/files/80188/demand.generation.aux.events.ENG.docx)

**Comment by bjornmeansbear** [comment]
Okay, I think you have what you need for this too.

**Comment by bjornmeansbear** [comment]
This is fixed and good to go I believe now too?

**Comment by mkamoss** [comment]
Yes, done!
