### ISSUE TITLE
tweaks to monday opening ceremony bios/photos - ENG & FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#149]
We need to move Surya Chandra and Oying's photos/bios to be at the end, since they are least important

We also need to add John Kerry's bio and photo (sorry, I just found out about this)

Hon. John F. Kerry (video message)
The United States Secretary of State

On February 1, 2013, John Forbes Kerry was sworn in as the 68th Secretary of State of the United States after 28 years in the United States Senate. In 2009, Secretary Kerry became Chairman of the Senate Foreign Relations Committee, assuming a leadership role on key foreign policy and national security issues facing the United States, including Afghanistan and Pakistan, nuclear nonproliferation, and global climate change. His service as Chairman built on his previous Senate work that included helping to expose the Iran-Contra scandal and leadership on global AIDS.

![john-kerry](https://cloud.githubusercontent.com/assets/16087472/12151319/8b608bac-b47c-11e5-8625-5a5f4f068651.jpg)
)

**Comment by mkamoss** [comment]
Also the timeline needs some formatting -- I think each speaker needs to be indented or something, to different them from the events? I can't remember what we did last time but it was fine so please replicate.

**Comment by mkamoss** [comment]
L’Honorable John F. Kerry (message vidéo)
Secrétaire d’État du gouvernement des Etats-Unis

John Forbes Kerry a prêté serment le 1er Février 2013 en tant que 68ème Secrétaire d’État des États-Unis, après avoir servi pendant 28 ans auprès du Sénat américain. En 2009, le Secrétaire Kerry est devenu Président de la Commission du Sénat pour les Relations Étrangères, s’engageant ainsi dans un rôle de leader sur les nombreuses questions de politique étrangère et de sécurité nationale auxquelles sont confrontés les États-Unis, y compris pour l’Afghanistan et le Pakistan, les questions de non-prolifération des armes nucléaires, et le changement climatique global. Son travail en tant que Président de la Commission s’est nourri de ses efforts précédents auprès du Sénat, qui avaient incluent le soutien des révélations sur le scandale Iran - Contra, et son leadership dans la lutte mondiale contre l’épidémie de SIDA.

**Comment by bjornmeansbear** [comment]
So there literally isn't room for doing any of this. I'll have to add another spread to both of these sections.

**Comment by mkamoss** [comment]
I was afraid of that.

**Comment by bjornmeansbear** [comment]
holy crap....... this is done. both languages.
