### ISSUE TITLE
addition to CEO Roundtables on Tuesday - ENG & FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#150]
Please add: 

Table 30
What does it take to be an effective, engaging and inspiring leader?
Jonathan D. Quick, President and CEO of Management Sciences for Health (MSH)

Jonathan D. Quick, MD, MPH is President and CEO of Management Sciences for Health (MSH). He is a family physician and health management specialist and has worked in international health since 1978. He has worked in over 50 countries in Africa, Asia, Latin America, and the Middle East. Dr. Quick’s prior roles include Director of Essential Drugs and Medicines Policy at the World Health Organization, founding Director of MSH’s drug management program/center for pharmaceutical management, and advisor for MSH projects in Afghanistan and Kenya.

Dr. Quick is senior editor of Managing Drug Supply and co-author of the Financial Times Guide to Executive Health. He is on the faculty of Harvard Medical School Department of Global Health and Social Medicine and Boston University School of Public Health, and is a Fellow of the Royal Society of Medicine.
![jq headshot-highres 2](https://cloud.githubusercontent.com/assets/16087472/12151867/4ed88ac4-b47f-11e5-901e-601cf783583d.jpg)

**Comment by mkamoss** [comment]
FR version: 

Table 30

Que faut-il pour devenir un leader efficace, captivant et enthousiasmant?

Jonathan D. Quick, Président et PDG de Management Sciences for Health (MSH)

Jonathan D. Quick, MD, MPH est Président et PDG de Management Sciences for Health (MSH). Il est médecin généraliste et spécialiste du management en santé et a travaillé dans le domaine de la santé internationale depuis 1978. Son expérience couvre plus de 50 pays en Afrique, Asie, Amérique Latine et au Moyen-Orient. Il a auparavant occupé le poste de Directeur pour les Politiques sur les Médicaments Essentiels et les Produits de Santé pour l’Organisation Mondiale de la Santé, Directeur et Fondateur du programme pour la gestion des médicaments / centre pour la gestion des produits pharmaceutiques de MSH, et conseillers pour les projets de MSH en Afghanistan et au Kenya.

Dr. Quick est un des principaux éditeurs de la revue “Managing Drug Supply” et co-auteur du Guide to Executive Health paru dans le Financial Times. Il fait partie du corps enseignant du Département de Santé Globale et de Médecine Social de l’École de Médecine de Harvard, et de l’École de Santé Publique de Boston University, et est également membre de la Royal Society of Medicine.

**Comment by bjornmeansbear** [comment]
Added to both!
