### ISSUE TITLE
Front Matter - FR

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#152]
I also destroyed the FR Front Matter assignment, sorry!! Please fix it back up.
I need to enter some aux events for Quality of Care and Demand Generation but didn't have space so please leave me some room. I will probably need about half a page for each list.

**Comment by bjornmeansbear** [comment]
You just need to add things in the French Front Matter? or the English one too?

**Comment by mkamoss** [comment]
I need to add these 2 in the FR, but I think I only need to do Demand Gen. in the ENG.

**Comment by bjornmeansbear** [comment]
k it seems like the only way to fit more things in is to add 2 more pages, I don't really see how two 1/2 pages of content will fit in those places otherwise. I guess I'll have to get back into the english one to see what to do there.

**Comment by bjornmeansbear** [comment]
okay, you should have room in the french version to add your stuff let me know if you need more tables setup or something.

I'll make some space in the english front matter too... whew!

**Comment by mkamoss** [comment]
All good now. Please take a look at the FR and ENG Tracks sections and make sure formatting is OK. Seems to be an extra page now at the end of the FR section.

**Comment by bjornmeansbear** [comment]
Okay, I think things are to normal there currently. There is an extra page at the end of both the Eng and French versions, just the way it worked out to fit all the stuff in. I can make that just conference at a glance page since it is on a spread but really only needs 1 page?

**Comment by mkamoss** [comment]
## That's fine - whatever you think is cool with me

Marianne Amoss
Communications Specialist
Bill & Melinda Gates Institute for Population and Reproductive Health
Johns Hopkins Bloomberg School of Public Health
615 N. Wolfe St.  W4041D
Baltimore, MD 21205  USA
Mobile: +1 443 600 0121 | Office: +1 410 502 9067
Skype: marianne.amoss
www.gatesinstitute.orghttp://www.gatesinstitute.org/ | "Like" us on Facebook https://www.facebook.com/TheGatesInstitute | Follow us on Twitter https://twitter.com/gatesjhu

**Comment by bjornmeansbear** [comment]
The french PDF has the conference at a glance the way I mentioned. Immediately after the tracks
