### ISSUE TITLE
MA - reminder to change the tracks titles to FR in FR Front Matter

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#153]
Just a reminder to me - nothing for KB to do

**Comment by bjornmeansbear** [comment]
Are those assigned to you? you can muck about with them? just want to make sure

**Comment by bjornmeansbear** [comment]
@mkamoss you're working on this?. you have access to everything you need to do this

**Comment by mkamoss** [comment]
Yes I will work on this

**Comment by mkamoss** [comment]
this is done and can be closed
