### ISSUE TITLE
FR version of shuttle sked copy

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#154]
Here is the copy that goes at the top of the shuttle schedule page: 

Informations sur les horaires des navettes:
Les navettes circulent toutes les 30 minutes entre les horaires de début et de fin de services indiqués dans la fiche horaire.
La navette pour l’aéroport part et termine à l’aéroport de Bali.
La navette circulant entre les différents lieux de la Conférence part et termine au Centre de Convention Nusa Dua
Les 24 et 25 janvier, toutes les navettes circulant entre les lieux de la Convention s’arrêteront au Westin Resort pour que les participants puissent récupérer leurs badges avant de se rendre au centre de convention.
Les horaires des navettes sont disponibles à la réception de chaque hôtel et à la réception de la CIPF située à l’aéroport. Pour plus de détail, merci de consulter: www.fpconference.org

**Comment by bjornmeansbear** [comment]
whew! I almost forgot about that!

**Comment by bjornmeansbear** [comment]
I assigned these as well, french and english covers, just incase.
