### ISSUE TITLE
fp2020 plenary - add Jagdish bio/headshot

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#156]
Did I give you this already? 
[jagdish FR.docx](https://github.com/OOKB/icfp/files/80688/jagdish.FR.docx)
![jagdish1](https://cloud.githubusercontent.com/assets/16087472/12161390/316e06fa-b4c3-11e5-9d1e-df2daf49666b.jpg)

**Comment by mkamoss** [comment]
NVM i'm doing this. i tried to delete but can't figure out how.

**Comment by bjornmeansbear** [comment]
He's in there already, unless I added him to the wrong place? I definitely added him somewhere

**Comment by bjornmeansbear** [comment]
yeah, he's there, but I somehow deleted the title to "part2" and couldn't undo it... can you enter that in?

**Comment by bjornmeansbear** [comment]
was able to undo and get the title back after all.

**Comment by mkamoss** [comment]
Yeah I meant the French version. I put him in.

Sent from my iPhone

On Jan 6, 2016, at 10:51 PM, Kristian Bj?rnard <notifications@github.com<mailto:notifications@github.com>> wrote:

He's in there already, unless I added him to the wrong place? I definitely added him somewhere

##
