### ISSUE TITLE
Sessions issues - day 1 (ENG)

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#160]
The only issues we have found with the sessions are in the first day -- the others look clean. WOOP
1. [x] on p. 59 there is a big white space at the top of the page -- seems like it shouldn't be there
2. [x] on p. 61 the sessions are out of order (starting with 1.1.17 and going to 1.1.20). and there is a strange big white space in the middle of the page - 1.1.19 and 1.1.20 are cut off at the bottom
3. [ ] on p.68 the sessions are out of order. maybe you did this because of how much space you had on the page? if so, OK -- we can leave as is.
4. [x] something happened on p. 70 where 1.4.19 and 1.4.20 are appearing in the middle of the 1.3.xx section. They need to be put in their correct place. 
5. [x] p. 71 is totally blank

**Comment by bjornmeansbear** [comment]
these are all due to it being too late... almost all solved.
