### ISSUE TITLE
one-for-one session swap

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#165]
We need to swap two sessions. Can you do this with your text box trick?

We swapped what we previously had as session 1.2.04 and session 1.4.04; the session numbers have changed. The corrected session info is below. **Let me know if this is confusing or if it is a giant problem.

1.2.04 Impact Evaluation Results from the Urban Reproductive Health Initiative (URHI) / Résultats de l'évaluation d'impact de l'Initiative de Santé Reproductive Urbaine (ISRU)
Tuesday 
12:00 PM - 1:20 PM 
Room: Kintamani 1

1.4.04 Access to and Use of Contraceptives by Adolescents: Donor, Researcher, Implementer and Youth Perspectives / Accès et utilisation de la contraception par les adolescents: Perspectives de bailleurs, chercheurs, responsables de programmes et jeunes
Tuesday 
4:20 PM - 5:40 PM 
Room: Kintamani 1

**Comment by bjornmeansbear** [comment]
okay! https://www.dropbox.com/s/495axsydx1qj8io/Screenshot%202016-01-07%2015.07.05.png?dl=0

and

https://www.dropbox.com/s/9o87uywrs2d3h2r/Screenshot%202016-01-07%2015.07.24.png?dl=0

look like their numbers have swapped. awesome.

AND,
2.2.03 has "TBC" as the moderator
https://www.dropbox.com/s/dvixufcranr2qm4/Screenshot%202016-01-07%2015.07.44.png?dl=0
