### ISSUE TITLE
quick aux events fix

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#167]
I had to make a quick aux events edit and now the Sponsoring Organizations thing is in the wrong place in the 2nd event on page 214. Can you fix? See screenshot.
<img width="447" alt="screen shot 2016-01-07 at 5 08 35 pm" src="https://cloud.githubusercontent.com/assets/16087472/12184131/6790e0d8-b561-11e5-853f-7b5054953187.png">

**Comment by mkamoss** [comment]
Same thing just happened on p. 217
<img width="472" alt="screen shot 2016-01-07 at 5 11 03 pm" src="https://cloud.githubusercontent.com/assets/16087472/12184173/b03f694e-b561-11e5-86ad-fafd0af05337.png">

**Comment by mkamoss** [comment]
And on p. 224
<img width="435" alt="screen shot 2016-01-07 at 5 12 02 pm" src="https://cloud.githubusercontent.com/assets/16087472/12184191/cd0e87d0-b561-11e5-83eb-a22d81df0821.png">

**Comment by bjornmeansbear** [comment]
:+1: thanks.

**Comment by mkamoss** [comment]
Got 2 corresponding fixes that are needed in the FR book --
I can't tell you the page #s because they are not right (still for the assignment and not the full InDesign file) but --
please look at the 2nd event under Mardi, 7-8:20
and
on p. 2 of Mercredi 18:00-19:30
and you'll see the same errors as I've described above.

**Comment by mkamoss** [comment]
While you're in there -- on the first full page of the on-site aux events descriptions, the title says: IN SITU ÉVÉNEMENTS SATELLITES
it should say: ÉVÉNEMENTS SATELLITES IN SITU

**Comment by bjornmeansbear** [comment]
English should be good to go. I'll fix the french ones soon.... (did make the in situ placement change)

**Comment by bjornmeansbear** [comment]
french fixed too.
