### ISSUE TITLE
quick fix p. 228

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#168]
I had to delete an event here so I am thinking you should just delete the horizontal rule and let this one event be the last on the page, so you don't have to reformat the pages that come after. See screenshot 
<img width="502" alt="screen shot 2016-01-07 at 5 12 59 pm" src="https://cloud.githubusercontent.com/assets/16087472/12184228/06e58422-b562-11e5-9f2c-306b74bef197.png">

**Comment by bjornmeansbear** [comment]
I think this got solved.
