### ISSUE TITLE
ENG - day tabs that need fixing

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#170]
- [x] 121 - change to SESSIONS - TIMEBLOCK 2 12:00 - 13:20
- [x] 202 - change to WEDNESDAY, 27 JANUARY
- [x] 232-236 - there is an extra 0 before the date in each of these
- [x] 241 - change to THURSDAY, 28 JANUARY
- [x] 27 - add "DEMAND GENERATION AND SOCIAL CHANGE"

**Comment by bjornmeansbear** [comment]
okay! first 5 down.
