### ISSUE TITLE
Possible 2015s that should be 2016s

### ISSUE THREAD

**Issue by bjornmeansbear** [OOKB/icfp#174]
- [x] PG 97 — Dr. Blum is the Co-chair of the ICFP 2015 Youth Sub-committee …
- [x] PG 96 — Chair: Dr. Kate Baye, Co-chair of the ICFP 2015 Youth Sub-committee …

Everything else seems legit.

**Comment by bjornmeansbear** [comment]
Is that to be ICFP 2016 now? Otherwise all the 2015s seem to be about things in 2015.

**Comment by mkamoss** [comment]
yes to both!

**Comment by bjornmeansbear** [comment]
Done!
