### ISSUE TITLE
Feed should not have byte order mark at the beginning of JSON text

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/icfp#3]
Implementations MUST NOT add a byte order mark to the beginning of a
  JSON text.  In the interests of interoperability, implementations
  that parse JSON texts MAY ignore the presence of a byte order mark
  rather than treating it as an error.

https://tools.ietf.org/html/rfc7159

**Comment by bjornmeansbear** [comment]
So this was the hex code thing... and it says if its UTF16 or UTF8 or whatever... but it breaks some JSON interpreters, so I should request that they no longer use it?

**Comment by webmasterkai** [comment]
If you feel like sending yet another email. They are including `FE FF 00`.

This link says `FE FF` is UTF-16, big endian https://msdn.microsoft.com/en-us/library/windows/desktop/dd374101(v=vs.85).aspx Issue #2 requests that we change it to UTF-8. Hopefully that takes care of this issue too.
