### ISSUE TITLE
Change SessionType value for each listed entity

### ISSUE THREAD

**Issue by webmasterkai** [OOKB/icfp#4]
The following should update the `SessionType` to `Preformed Panel` instead of `Preformed_Panel`.

`[16418, 16468, 16470, 16390, 16385, 16510, 16370, 16530]`

**Comment by bjornmeansbear** [comment]
I emailed them requesting a fix, or at least an explanation ;)

**Comment by webmasterkai** [comment]
Updated list: `[16468,16609,16345,16366,16386,16611,16418,16385,16508]`

**Comment by bjornmeansbear** [comment]
weird. some gone, and some new ones added... wtf.

**Comment by bjornmeansbear** [comment]
They went through and fixed these.
