### ISSUE TITLE
Make new shuttle schedule page

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#85]
Can you update the shuttle schedule (inside front cover) and send me a PDF, so I can post it on the website?
[shuttle sked revised.docx](https://github.com/OOKB/icfp/files/48922/shuttle.sked.revised.docx)

**Comment by bjornmeansbear** [comment]
Awesome! thanks for doing this here. Will do.

**Comment by mkamoss** [comment]
Can I get this by the end of the week? We need it for the mobile app. Thanks!

**Comment by bjornmeansbear** [comment]
emailed them too you. Also in the ICFP booklet Cover folder.

**Comment by mkamoss** [comment]
I need a couple more edits on this page. 
In the sentence that starts "On 24 and 25 January" please change "all shuttles" to "all Venue Shuttles" --  "On 24 and 25 January, all Venue Shuttles will make a stop ..."
Also, the sentence at the top that is the largest is the least important ("Shuttle schedules are available ...). The other 3 sentences are much more important. Can you weight them more heavily and make that first sentence smaller? Essentially you'll need to reverse the formatting.
Let me know if you have questions -- thanks!

**Comment by mkamoss** [comment]
Hey there, could you tackle this today? We need to submit stuff for the mobile app today. Thanks!

**Comment by bjornmeansbear** [comment]
Can the first sentence be last then, sort of the fine print?

**Comment by mkamoss** [comment]
Sure!

**Comment by bjornmeansbear** [comment]
Done. Shall I email them to you? or can you find them in the ICFP booklet folder, clearly marked as "ShuttleMaps-20151214"

**Comment by mkamoss** [comment]
Got them. Thanks!

**Comment by mkamoss** [comment]
Hi, just got word that the shuttle is now ending its run at 21:00 on 26 and 27 Jan. See attached. Can you please update in the program and provide me with new PDFs? 
![roll up banner hospitality desk-01-01-01](https://cloud.githubusercontent.com/assets/16087472/11940739/9a2b003a-a7f8-11e5-930c-4820f39a8522.jpg)

**Comment by bjornmeansbear** [comment]
Updated the docs on Dropbox.
