### ISSUE TITLE
replace Bayer logo on p. 4

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#86]
With one of the .eps files in this folder: https://www.dropbox.com/sh/q9k1rjpcrla81vp/AABb6bAtYHKzUQrimvJSdpfva?dl=0
They are getting rid of the "Science for a Better Life" tagline

**Comment by bjornmeansbear** [comment]
done in English version, still need to do in French version.

**Comment by bjornmeansbear** [comment]
done in both versions.

**Comment by mkamoss** [comment]
I don't see the updated logo in the InCopy assignment ... do you need to update or something?

**Comment by bjornmeansbear** [comment]
Hmm, I just told it to update the assignment, maybe try it now?

**Comment by mkamoss** [comment]
All good now! Thanks.
