### ISSUE TITLE
make "Core Group" and "Sponsors" headers larger on p. 4, English and French

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#90]

**Comment by bjornmeansbear** [comment]
Complete.

![screenshot 2015-12-08 23 34 42](https://cloud.githubusercontent.com/assets/324987/11676790/4a4532aa-9e04-11e5-8196-366c3d4eaedd.png)

![screenshot 2015-12-08 23 35 17](https://cloud.githubusercontent.com/assets/324987/11676792/5a52423c-9e04-11e5-8844-63a9fbc76fa9.png)
