### ISSUE TITLE
French assignments

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#92]
As you work through the French book, can you set up the assignments for me? I am ready to work in Front Matter so that's the only one I need today.

**Comment by bjornmeansbear** [comment]
sorry! get to this in a sec

**Comment by bjornmeansbear** [comment]
They should be showing up shortly in the dropbox

**Comment by bjornmeansbear** [comment]
French Frontmatter, Check.

**Comment by bjornmeansbear** [comment]
So, I'll go through the rest of the french sections today and get them assigned to you? I'll also find out what else is f-ed up...

**Comment by mkamoss** [comment]
Sounds good. My translator is working on the content now and will have it back to me tomorrow so if you could get things cleaned up today that'd be great.

**Comment by bjornmeansbear** [comment]
As these are entered, the assignments will happen.... just missing a few of the session days I think is all thats left.
