### ISSUE TITLE
not a program issue but whatever

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#93]
Do you have a file of the batik repeating that you can send me? We need to use it as a background for something, and I only have the file of the individual shape, not as a pattern. Thanks!

**Comment by bjornmeansbear** [comment]
the <> shape? you want a whole filled page of it basically?

**Comment by bjornmeansbear** [comment]
I don't seem to have the other pattern, I'm not sure where/how I got that one into the booklet...

**Comment by mkamoss** [comment]
I know we had it somewhere but I don't know where ... I can ask Juliana.

**Comment by mkamoss** [comment]
Hey, could you make me a whole page of the design, please? I can't find it anywhere.
