### ISSUE TITLE
CEO Roundtables

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#94]
- Delete table 22 from Tuesday
- Delete table 32 from Wednesday
- Replace headshot of Vinoj Manning (table 30, Tuesday) with the attached
  ![vinoj manning](https://cloud.githubusercontent.com/assets/16087472/11852752/c2c0c54c-a407-11e5-9479-849adda6a2a6.jpg)

**Comment by mkamoss** [comment]
Add Pape Gaye to Tuesday:

Pape Gaye, President and CEO, IntraHealth International
Table 28

For over three decades, Pape Amadou Gaye has advocated for, built, and leveraged strong partnerships with governments, nongovernmental organizations, and the private sector to catalyze change and enable health workers to better serve communities in need. A native of Senegal, Gaye began his career in international development as a trainer of Peace Corps volunteers in Senegal and Benin. As the director of IntraHealth International’s regional office for West, Central, and North Africa, Gaye focused on improving the performance of health workers and health systems to more effectively serve clients and communities with quality care. Now as the President and CEO of IntraHealth, Gaye continues to pursue his lifelong commitment by collaborating with leaders in developing countries to encourage sustainable development in vulnerable communities. He also continues to advocate for family planning, especially in his native West Africa, as a high-impact solution to address health and population challenges.

Under Gaye’s leadership, IntraHealth has garnered a strong reputation as an organization that fosters local solutions to health care challenges by improving health worker performance, strengthening health systems, harnessing technology, and leveraging partnerships. As an expert on the global health worker crisis, family planning and human capacity building, Gaye speaks and writes extensively on these subjects. He holds an MBA from the University of California at Los Angeles and has also previously worked for the 1984 Los Angeles Olympic Committee and the Centers for Disease Control and Prevention.

Here's his headshot:
![gaye-2011_web](https://cloud.githubusercontent.com/assets/16087472/11941696/74f6d968-a7ff-11e5-9a24-ab5ec734ca95.jpg)

**Comment by bjornmeansbear** [comment]
Does Papa Gaye replace Halida Hanum Akhter, 
She's currently listed at Table 28 for tuesday

**Comment by mkamoss** [comment]
Hrmmm that's a good question. I don't have my work computer with me so can't open the assignment to see if I made a mistake or forgot to mention her ... but at any rate, the program should match what's here: http://fpconference.org/2016/program/roundtables/ceos-for-emerging-leaders-roundtables/?

**Comment by bjornmeansbear** [comment]
Great. Some of the table numbers look like they moved a bit, Halida Hanum
Akhter is at a different # now.
cool.

**Comment by mkamoss** [comment]
Oh yeah, I see her now on the webpage. Should've checked there myself!

**Comment by bjornmeansbear** [comment]
Updated. Changed Table#s to match webpage.
