### ISSUE TITLE
Marketplace of Ideas adjustment

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#96]
I edited Marketplace of Ideas, adding titles to each presentation and cutting a few, so the pages got messed up. Can you please fix?

**Comment by mkamoss** [comment]
Also if the Medium font weight isn't working for the presentation titles, feel free to change it to something else. I wanted something that was less heavy than Bold but still obvious, and I didn't think italic was a good choice.

**Comment by bjornmeansbear** [comment]
What about the Serif typeface instead?

**Comment by mkamoss** [comment]
Works for me!

Sent from my iPhone

On Dec 18, 2015, at 12:31 AM, Kristian Bj?rnard <notifications@github.com<mailto:notifications@github.com>> wrote:

What about the Serif typeface instead?

##

**Comment by bjornmeansbear** [comment]
When does wednesday the 27th stuff start? with "The Power of SMART: One Simple Secret to Effective Advocacy " ???

**Comment by mkamoss** [comment]
Yep.

If you need to reference anything else, you can check the lists here: http://fpconference.org/2016/program/marketplace-of-ideas/?

Everything should match up.

**Comment by bjornmeansbear** [comment]
Oh, perfect.

**Comment by mkamoss** [comment]
?The advantage to having all this stuff already figured out! There should be a lot fewer changes on the fly this time. :)

**Comment by bjornmeansbear** [comment]
This should be up to date and good to go.
