### ISSUE TITLE
Monday Plenary change

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#97]
Please delete Melinda Gates from p. 37

**Comment by mkamoss** [comment]
on p. 41 please replace Sir Chris Hohn's bio with this one:

Sir Christopher Hohn is the co-founder of the Children’s Investment Fund Foundation. CIFF is the world’s largest foundation that focuses specifically on improving children’s lives. Supported by an endowment of $4.6 billion, it seeks extraordinary change to seemingly intractable challenges for children. Areas of work include children and mothers’ health and nutrition, children’s education, deworming and welfare, and smart ways to slow down and stop climate change. The foundation was established in 2004. With a rigorous business-like approach to philanthropic funding. It focused on clear returns for children from the outset. The emphasis on data to measure impact has been widely adopted by other development funders.

Chris is the Managing Partner and Portfolio Manager of the London-based hedge fund The Children’s Investment Fund (TCI). Before setting up TCI, he managed investment strategies for other hedge funds for almost a decade. He received an MBA from Harvard Business School and a BSc in accounting and economics from Southampton University in the UK. In 2014, he was knighted for services to philanthropy.

**Comment by bjornmeansbear** [comment]
Updated.
