### ISSUE TITLE
Tuesday Plenary changes

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#98]
Delete CK Mishra and replace with: 

Jagat Prakash Nadda (invited)
Union Minister of Health and Family Welfare

Jagat Prakash Nadda is an Indian politician. He is currently the Union Minister of Health and Family Welfare and member of Rajya Sabha from Himachal Pradesh and Parliamentary Board Secretary of Bharatiya Janata Party. Earlier, he was a Minister in Himachal Pradesh Government.

![jagat](https://cloud.githubusercontent.com/assets/16087472/11942568/7a5f46a0-a805-11e5-9656-b5dcc3db62ae.jpg)

**Comment by bjornmeansbear** [comment]
That image is too small, any chance there is a larger one?

**Comment by bjornmeansbear** [comment]
something at least 400px wide... It needs to be about twice as large if possible to be printable with quality.

**Comment by bjornmeansbear** [comment]
Text is in.

**Comment by bjornmeansbear** [comment]
Made the image work.... won't be too bad.

**Comment by mkamoss** [comment]
Ok. I've asked anyway about a larger image. So if we get a better one, great; if not, fine.

Sent from my iPhone

On Dec 21, 2015, at 10:30 PM, Kristian Bj?rnard <notifications@github.com<mailto:notifications@github.com>> wrote:

Made the image work.... won't be too bad.

##
