### ISSUE TITLE
Wednesday plenary changes

### ISSUE THREAD

**Issue by mkamoss** [OOKB/icfp#99]
Delete Babatunde Osotimehin on p. 95

**Comment by mkamoss** [comment]
Add Julia Bunting:

Julia Bunting
President, Population Council

Julia Bunting became the ninth president of the Population Council in March 2015. Ms. Bunting is widely known for her path-breaking work on reproductive and maternal health during her 12-year tenure at the UK Department for International Development (DFID), where she oversaw the UK government’s international development policy on HIV and AIDS; maternal, newborn, and child health; sexual and reproductive health and rights; and population.

Most recently, she served as a director at the International Planned Parenthood Federation (IPPF), where she led the Federation’s Programme and Technical areas. In June 2013, Ms. Bunting was awarded the honor of Officer of the Order of the British Empire (OBE) by Her Majesty Queen Elizabeth II for improving reproductive health in developing countries.

Ms. Bunting has served on the boards of several global health partnerships, including the Health Metrics Network (HMN), the Partnership for Maternal, Newborn and Child Health (PMNCH), and the Reproductive Health Supplies Coalition (RHSC). She served as chair of the RHSC for four years. She has authored numerous research publications on population trends, family planning, and public health.

![juliabunting_ldr_154_212_s](https://cloud.githubusercontent.com/assets/16087472/11942649/0378d0aa-a806-11e5-8f65-66052d94f317.jpg)

**Comment by mkamoss** [comment]
Replace Presentation 4 on p. 98 with this:

Presentation 4: Indonesia Oral Contraceptive Ambassador Program

Rosalina Sutadi
President Director of Bayer Indonesia

Rosalina Sutadi is Head of Business Unit Women’s HealthCare in Bayer Indonesia. Rosalina has more than 20 year experiences in pharmaceutical industry in Indonesia. She joined Bayer in 2001 as Head of Medical and Regulatory before she took responsibility in Marketing Women’s HealthCare.

She is Medical Doctor by training from University of Indonesia and holds a Master degree in Business Administration at Swiss German University, Indonesia.

![rosalina-sutadi](https://cloud.githubusercontent.com/assets/16087472/11942755/b6c64110-a806-11e5-8b37-94482bd4c97d.jpg)

**Comment by mkamoss** [comment]
Delete Presentation 5 from p. 98
(but leave Oying as Chair)

**Comment by bjornmeansbear** [comment]
For the future, so that updates/changed can be easily "checked off" and project managed (or easily confirmed that they are done or not done), each one of these should probably be its own "issue"

**Comment by bjornmeansbear** [comment]
These should all be correct now.

**Comment by mkamoss** [comment]
That's fine going forward - I was keeping everything in each plenary/day together for ease of use but I definitely see what you mean.

Sent from my iPhone

On Dec 21, 2015, at 10:46 PM, Kristian Bj?rnard <notifications@github.com<mailto:notifications@github.com>> wrote:

For the future, so that updates/changed can be easily "checked off" and project managed (or easily confirmed that they are done or not done), each one of these should probably be its own "issue"

##
